export const countryCodes = [
  { label: "Peru", code: "+51", flag: "🇵🇪" },
  { label: "United States", code: "+1", flag: "🇺🇸" },
  { label: "Mexico", code: "+52", flag: "🇲🇽" },
  { label: "Argentina", code: "+54", flag: "🇦🇷" },
  { label: "Chile", code: "+56", flag: "🇨🇱" },
  { label: "Colombia", code: "+57", flag: "🇨🇴" },
  { label: "Brazil", code: "+55", flag: "🇧🇷" },
  { label: "Ecuador", code: "+593", flag: "🇪🇨" },
  { label: "Bolivia", code: "+591", flag: "🇧🇴" },
  { label: "Venezuela", code: "+58", flag: "🇻🇪" },
  { label: "Uruguay", code: "+598", flag: "🇺🇾" },
  { label: "Paraguay", code: "+595", flag: "🇵🇾" },

  { label: "Spain", code: "+34", flag: "🇪🇸" },
  { label: "France", code: "+33", flag: "🇫🇷" },
  { label: "Germany", code: "+49", flag: "🇩🇪" },
  { label: "Italy", code: "+39", flag: "🇮🇹" },
  { label: "Portugal", code: "+351", flag: "🇵🇹" },
  { label: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { label: "Netherlands", code: "+31", flag: "🇳🇱" },
  { label: "Belgium", code: "+32", flag: "🇧🇪" },
  { label: "Switzerland", code: "+41", flag: "🇨🇭" },
  { label: "Austria", code: "+43", flag: "🇦🇹" },
  { label: "Sweden", code: "+46", flag: "🇸🇪" },
  { label: "Norway", code: "+47", flag: "🇳🇴" },
  { label: "Finland", code: "+358", flag: "🇫🇮" },
  { label: "Denmark", code: "+45", flag: "🇩🇰" },
  { label: "Poland", code: "+48", flag: "🇵🇱" },
  { label: "Czech Republic", code: "+420", flag: "🇨🇿" },
  { label: "Greece", code: "+30", flag: "🇬🇷" },
  { label: "Turkey", code: "+90", flag: "🇹🇷" },

  { label: "Japan", code: "+81", flag: "🇯🇵" },
  { label: "South Korea", code: "+82", flag: "🇰🇷" },
  { label: "China", code: "+86", flag: "🇨🇳" },
  { label: "India", code: "+91", flag: "🇮🇳" },
  { label: "Singapore", code: "+65", flag: "🇸🇬" },
  { label: "Malaysia", code: "+60", flag: "🇲🇾" },
  { label: "Thailand", code: "+66", flag: "🇹🇭" },
  { label: "Vietnam", code: "+84", flag: "🇻🇳" },
  { label: "Indonesia", code: "+62", flag: "🇮🇩" },
  { label: "Philippines", code: "+63", flag: "🇵🇭" },

  { label: "Australia", code: "+61", flag: "🇦🇺" },
  { label: "New Zealand", code: "+64", flag: "🇳🇿" },

  { label: "South Africa", code: "+27", flag: "🇿🇦" },
  { label: "Nigeria", code: "+234", flag: "🇳🇬" },
  { label: "Egypt", code: "+20", flag: "🇪🇬" },
  { label: "Morocco", code: "+212", flag: "🇲🇦" },
  { label: "Kenya", code: "+254", flag: "🇰🇪" },

  { label: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { label: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { label: "Israel", code: "+972", flag: "🇮🇱" },
  { label: "Qatar", code: "+974", flag: "🇶🇦" },
  { label: "Kuwait", code: "+965", flag: "🇰🇼" },
];
